### ISSUE TITLE
bug: specific class definition pattern produces ERROR nodes

### ISSUE THREAD

**Issue by lljbash** [tree-sitter/tree-sitter-cpp#264] opened 2024-05-06 10:33 UTC
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.22.2

### Describe the bug

![image](https://github.com/tree-sitter/tree-sitter-cpp/assets/11871224/817e1b59-3073-474f-85ba-668d92592760)
![image](https://github.com/tree-sitter/tree-sitter-cpp/assets/11871224/63528f93-93cf-40c6-884b-59a76be44212)

### Steps To Reproduce/Bad Parse Tree

combining class + macro + access identifier + using statement

### Expected Behavior/Parse Tree

The `using` statement should be recognized as an alias declaration node.

### Repro

```cpp
#define MACRO /*no-op*/

class MACRO Class {
public:
  using A = int;
};
```

**Comment by amaanq** [comment] 2024-08-16 23:40
duplicate of #85

**Closed by amaanq** 2024-08-16 23:40 UTC
Labels: bug
