### ISSUE TITLE
Error on multiple names for same struct in definition

### ISSUE THREAD

**Issue by genotrance** [tree-sitter/tree-sitter-cpp#32] opened 2019-01-28 18:04 UTC
Snippet is adapted from [FreeImage.h](https://github.com/imazen/freeimage/blob/master/Source/FreeImage.h#L208).

```c
typedef struct tagBITMAPINFOHEADER{
  int biClrImportant;
} BITMAPINFOHEADER, *PBITMAPINFOHEADER;
```

This compiles fine in gcc but fails in tree-sitter.

```
(translation_unit 1 1 97
 (type_definition 1 1 97
  (struct_specifier 1 9 51
   (type_identifier 1 16 19)
   (field_declaration_list 1 35 25
    (field_declaration 2 3 19
     (primitive_type 2 3 3)
     (field_identifier 2 7 14)
    )
   )
  )
  (ERROR 3 3 17
   (type_identifier 3 3 16)
  )
  (pointer_declarator 3 21 18
   (type_identifier 3 22 17)
  )
 )
)
```

**Comment by maxbrunsfeld** [comment] 2019-01-28 18:12
It looks like This is a duplicate of #30.

**Closed by maxbrunsfeld** 2019-01-28 18:12 UTC

**Comment by genotrance** [comment] 2019-01-28 18:22
Whoops!
