### ISSUE TITLE
Hightlight error in qt

### ISSUE THREAD

**Issue by chen244** [tree-sitter/tree-sitter-cpp#137] opened 2021-11-28 15:33 UTC
It meet QT_BEGIN_NAMESPACE and turn error
![image](https://user-images.githubusercontent.com/60290287/143774745-2e4ad418-0f02-4255-80e7-66ffd1b3a50a.png)

**Comment by jdrouhard** [comment] 2021-12-13 18:41
Dupe of #85.

**Closed** 2021-12-13 18:42 UTC
