### ISSUE TITLE
Error with Semicolon Following Member Function

### ISSUE THREAD

**Issue by berchn** [tree-sitter/tree-sitter-cpp#119] opened 2021-06-11 19:21 UTC
Class definitions allow for one optional semicolon following a member function (prior to C++14) or an arbitrary amount of semicolons (C++14 and after). Currently, an error occurs when parsing a member function followed by a semicolon:
```
class C { void f() { return; }; };

translation_unit [0, 0] - [1, 0]
  class_specifier [0, 0] - [0, 33]
    name: type_identifier [0, 6] - [0, 7]
    body: field_declaration_list [0, 8] - [0, 33]
      function_definition [0, 10] - [0, 30]
        type: primitive_type [0, 10] - [0, 14]
        declarator: function_declarator [0, 15] - [0, 18]
          declarator: field_identifier [0, 15] - [0, 16]
          parameters: parameter_list [0, 16] - [0, 18]
        body: compound_statement [0, 19] - [0, 30]
          return_statement [0, 21] - [0, 28]
      ERROR [0, 30] - [0, 31]
```
This could be addressed by allowing the empty statement in a class definition's body.

**Comment by jdrouhard** [comment] 2021-09-26 21:50
Dupe of #35

**Closed by jdrouhard** 2021-09-26 21:50 UTC
Labels: duplicate
