### ISSUE TITLE
[BUG] Code parsing error

### ISSUE THREAD

**Issue by cyw3** [tree-sitter/tree-sitter-cpp#232] opened 2023-11-01 07:05 UTC
The following code parses error:

```c

#include "test.h"

int test ( int a )
{
    if ( a<0 ) return 1;
    return 0;
}

int main ( void )
{
    int c = 0;
    if ((c = test(a)) < 0) {
        if (c == 2) {
        }
    }
}

```

The sexp of `(c = test(a))` is `(parenthesized_expression (ERROR (identifier)) (call_expression function: (identifier) arguments: (argument_list (identifier))))`. 
And the sexp of `c =` is `(ERROR (identifier))` while i think it is a `assignment`.

**Comment by cyw3** [comment] 2023-11-02 03:36
#212

**Comment by jdrouhard** [comment] 2023-11-15 00:43
Duplicate of those linked issues

**Closed** 2023-11-15 00:43 UTC
