### ISSUE TITLE
Macros breaks parsing

### ISSUE THREAD

**Issue by Shatur** [tree-sitter/tree-sitter-cpp#136] opened 2021-11-08 20:56 UTC
### Describe the bug

The following code:

```cpp
class Foo {
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "io.crow_translate.CrowTranslate.MainWindow")
    Q_DISABLE_COPY(MainWindow)

private:
    void changeEvent(QEvent *event) override;
};
```

Have a wrong matching for `QEvent` type because of `private` keyword.

Here is the tree from Neovim Playground:

```
  labeled_statement [146, 0] - [147, 45]
    label: statement_identifier [146, 0] - [146, 7]
    ERROR [147, 4] - [147, 8]
      primitive_type [147, 4] - [147, 8]
    expression_statement [147, 9] - [147, 45]
      call_expression [147, 9] - [147, 35]
        function: identifier [147, 9] - [147, 20]
        arguments: argument_list [147, 20] - [147, 35]
          binary_expression [147, 21] - [147, 34]
            left: identifier [147, 21] - [147, 27]
            right: identifier [147, 29] - [147, 34]
      ERROR [147, 36] - [147, 44]
```

### To Reproduce

1. Open the following file at the following line: https://github.com/crow-translate/crow-translate/blob/400c2432e37f64e7c65b5fd87add02ce5b34a005/src/mainwindow.h#L148

### Expected behavior

`QEvent` should be a type. Playground shouldn't contain `ERROR`.

**Comment by theHamsta** [comment] 2021-11-09 00:56
It would be helpful if you could condense the given source file to a more minimal but complete example.
Just having the following, doesn't trigger the error.
```
class Foo {
private:
    void changeEvent(QEvent *event) override;
};
```

This seems to be causes by the Q_OBJECT marcos at the beginning of the file
```
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "io.crow_translate.CrowTranslate.MainWindow")
    Q_DISABLE_COPY(MainWindow)
```

```
class Foo {

    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "io.crow_translate.CrowTranslate.MainWindow")
    Q_DISABLE_COPY(MainWindow)

private:
    void changeEvent(QEvent *event) override;
};
```

**Comment by Shatur** [comment] 2021-11-09 08:55
Oh, you are right. The issue caused by macros. Update the issue.

**Comment by jdrouhard** [comment] 2021-11-11 03:53
Dupe of #85. Macros cannot be 100% correctly parsed by a grammar that isn't contextually aware and doesn't run the preprocessor, unfortunately. These ambiguities will always rely on tree-sitter's error recovery.

**Closed by jdrouhard** 2021-11-11 03:54 UTC
