### ISSUE TITLE
Error detected while processing BufReadPost Autocommands for "*"

### ISSUE THREAD

**Issue by Galicarnax** [tree-sitter/tree-sitter-cpp#198] opened 2023-04-01 15:36 UTC
After recent TS update, I get this when opening `cpp` files:
```
Error detected while processing BufReadPost Autocommands for "*":                                                                                              
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:22: Error executing lua: /usr/share/nvim/runtime/filetype.lua:23: Vim(append):Error executing lua call
back: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid structure at position 347 for language cpp
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: in function 'get_query'
        ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:108: in function 'get_query'
        ...ite/pack/packer/start/nvim-gps/lua/nvim-gps/internal.lua:11: in function 'is_supported'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:387: in function 'is_enabled'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:507: in function 'attach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
```
Also, when I try to save the file, nvim says `File exists (add ! to override)`.
When I do `:TSUninstall cpp` the bug goes away.

**Comment by Galicarnax** [comment] 2023-04-01 15:42
When I do `TSUninstall cpp` and then `TSInstall cpp`, it compiles the parser, and then gives this error:
```
Failed to execute the following command:                                                                                                                          
{
  cmd = <function 1>
}
```

**Comment by Fildo7525** [comment] 2023-04-07 13:33
I encountered the same issue. Hope this will be fixed ASAP.

**Comment by Fildo7525** [comment] 2023-04-07 14:07
Shouldn't this be similar to  https://github.com/nvim-treesitter/nvim-treesitter/issues/3054?

**Comment by Galicarnax** [comment] 2023-04-16 11:54
I don't see how they are similar. And I guess, this current bug does not affect many users (if it did, it would render itself unusable to many, and would be quickly fixed; yet, it's still not fixed, even after yesterday's update of the cpp parser). I'm using the latest versions of neovim and of tree-sitter (and of all other plugings), and `checkhealth` does not report any errors with `nvim-treesitter`.

**Comment by Fildo7525** [comment] 2023-04-16 16:52
I have fixed the issue. It's caused by nvi-gps because it i deprecated plugin try looking up nvim.nvim. it is a good replacement

**Comment by Galicarnax** [comment] 2023-04-16 17:01
Bingo! I also had `nvim-gps`. I removed it and the error is gone. Left to wonder how you traced it... When I tried, I haven't noticed any connection with `nvim-gps`. The message clearly hinted at an error in treesitter queries.

Many thanks!

**Closed** 2023-04-16 17:01 UTC

**Comment by mlysle** [comment] 2023-08-23 02:40
Similar problem - caused by a rainbow parentheses plugin that had been deprecated. Leaving this here if it helps anyone solve their issue.
