### ISSUE TITLE
decltype, constexpr, and template interaction

### ISSUE THREAD

**Issue by 3719e04** [tree-sitter/tree-sitter-cpp#186] opened 2023-01-08 04:33 UTC
There is some issue in #67 . With the following snippet,
```cpp
#include <array>
struct Foo {
  constexpr static int bar = 0;
};
int main() {
  Foo foo;
  std::array<int, decltype(foo)::bar> test;
  std::array<std::array<int, decltype(foo)::bar>, 10> everything_below_this_line_break;
  return 0;
}
```
we get some highlighted results similar to this
<img width="833" alt="fig" src="https://user-images.githubusercontent.com/56977205/211180528-c18c2e88-40c2-4cd7-93ff-5f16c976ae57.png">

As we can see, the parser doesn't work as expected after line 8.

**Comment by jdrouhard** [comment] 2023-01-08 20:26
Did you update nvim-treesitter recently, just prior to seeing this?

**Comment by 3719e04** [comment] 2023-01-08 20:55
I just update to [3e31620](https://github.com/nvim-treesitter/nvim-treesitter/commit/3e316204f8ec8450bbaace69d0bf8fe332633fec) and this issue persists.

**Comment by jdrouhard** [comment] 2023-01-08 20:57
I mean, when did you start seeing it? The current HEAD of nvim-treesitter has what I believe to be a broken version of this parser, which should be fixed after the next parser update.

**Comment by jdrouhard** [comment] 2023-01-08 20:59
Fixed by https://github.com/tree-sitter/tree-sitter-cpp/commit/5b7e264bc6354bb6f654cd01b24ac0289f889d4a

**Closed by jdrouhard** 2023-01-08 20:59 UTC

**Comment by jdrouhard** [comment] 2023-01-09 03:28
Fixed underlying issue with decltype (the actual error caused by your example) in https://github.com/tree-sitter/tree-sitter-cpp/commit/2b908639fd35a437dde88ca3e659cba786620eae
